/* @layer root-config @kind config (managed: generated by brock sync, do not edit) */
module.exports = async () => {
  const { loadBuilderConfig } = await import('@drizztdourden08/brock-build/builder');
  return loadBuilderConfig(__dirname);
};
