// generated by brock sync, do not edit
import type { RendererBootTask } from '@drizztdourden08/brock-react';
import welcomeTask from '../src/boot/welcome.task';

const rendererBootTasks: RendererBootTask[] = [
  { ...welcomeTask, id: 'welcome' },
];

export { rendererBootTasks };
