// generated by brock sync, do not edit
import type { PreloadNamespace } from '@drizztdourden08/brock-electron/preload';

const preloadNamespaces: PreloadNamespace[] = [];

export { preloadNamespaces };
