// generated by brock sync, do not edit
import type { RendererModule } from '@drizztdourden08/brock-react';
import updaterRenderer from '@drizztdourden08/brock-updater/renderer';

const rendererModules: RendererModule[] = [
  updaterRenderer,
];

export { rendererModules };
