// generated by brock sync, do not edit
import type { MainModule } from '@drizztdourden08/brock-electron/main';
import updaterMain from '@drizztdourden08/brock-updater/main';

const mainModules: MainModule[] = [
  updaterMain,
];

export { mainModules };
