// generated by brock sync, do not edit
import type { AppReview } from '@drizztdourden08/brock-react';

const appReview: AppReview = {
  seed: () => import('../src/review/seed'),
  steps: [
    { id: 'notes', load: () => import('../src/review/notes.step') },
  ],
};

export { appReview };
