// generated by brock sync, do not edit
import type { AppReview } from '@drizztdourden08/brock-react';

const appReview: AppReview = {
  seed: () => import('../src/review/seed'),
  steps: [
    { id: 'notes', load: () => import('../src/review/notes.step') },
  ],
  fixtures: [
    { path: 'notes/review-note.txt', load: () => import('../src/review/fixtures/notes/review-note.txt?url') },
  ],
};

export { appReview };
