// generated by brock sync, do not edit
import { buildScreenTree } from '@drizztdourden08/brock-react';
import config from '../src/screens/screens.config';
import CreditsCard, { meta as creditsCardMeta } from '../src/screens/credits.card';
import GameGeneralSettings, { meta as gameGeneralSettingsMeta } from '../src/screens/game/general.settings';
import GameHomeHero, { meta as gameHomeHeroMeta } from '../src/screens/game/home.hero';

const screenTree = buildScreenTree(config, [
  { kind: 'card', id: 'credits', component: CreditsCard, meta: creditsCardMeta },
  { kind: 'settings', bucket: 'game', id: 'general', sections: GameGeneralSettings, meta: gameGeneralSettingsMeta },
  { kind: 'hero', bucket: 'game', id: 'home', component: GameHomeHero, meta: gameHomeHeroMeta },
]);

export { screenTree };
