// generated by brock sync, do not edit
import { buildSearchIndex } from '@drizztdourden08/brock-react';
import config from '../src/screens/screens.config';

const searchIndex = buildSearchIndex(config, [
  {"kind":"card","id":"credits","title":"Credits","icon":"file-text"},
  {"kind":"custom","id":"controls","bucket":"game","title":"Controls","icon":"keyboard","keywords":["bindings","keys","gamepad"],"entries":[{"label":"Jump","keywords":["space","button","a"],"anchor":"jump","description":"Space or button A"},{"label":"Interact","keywords":["e","button","x"],"anchor":"interact","description":"E or button X"},{"label":"Pause","keywords":["escape","start"],"anchor":"pause","description":"Escape or Start"}]},
  {"kind":"settings","id":"general","bucket":"game","title":"General","icon":"settings","sections":[{"id":"window","title":"Window","rows":[{"key":"windowMode","label":"Window mode","description":"Windowed, borderless or fullscreen.","hint":"Pick how the window sits on the screen. It changes right away.","keywords":[]},{"key":"startFullscreen","label":"Start fullscreen","description":"Open in fullscreen on launch.","hint":"On, the app opens fullscreen the next time it starts. The window you have now stays as it is.","keywords":[]}]},{"id":"audio","title":"Audio","rows":[{"key":"enableAudio","label":"Audio","description":"Play sound.","hint":"Off mutes every sound the app plays, whatever the volume.","keywords":[]},{"key":"masterVolume","label":"Master volume","description":"Overall output level.","hint":"Drag to scale every sound at once. 100% plays them as made.","keywords":[]}]},{"id":"developer","title":"Developer","rows":[{"key":"developerToolsEnabled","label":"Developer tools","description":"Allow opening the developer tools.","hint":"On, the menu shows the developer entries and the shortcut opens the browser developer tools.","keywords":[]},{"key":"allowDebugLogging","label":"Debug logging","description":"Write debug lines to the session log.","hint":"On, the session log keeps the detailed lines that help when you report a bug. The log grows faster.","keywords":[]}]}]},
  {"kind":"hero","id":"home","bucket":"game","title":"Home","icon":"house","keywords":["start","overview","profile"]},
]);

export { searchIndex };
