// generated by brock sync, do not edit
import { toursFromFiles } from '@drizztdourden08/brock-react';
import welcomeTour from '../src/tours/welcome.tour';

const appTours = toursFromFiles([
  { id: 'welcome', tour: welcomeTour },
]);

export { appTours };
