// generated by brock sync, do not edit
import { widgetsFromFiles } from '@drizztdourden08/brock-react';
import NotesWidget, { meta as notesWidgetMeta } from '../src/widgets/notes.widget';
import appWidgetLayout from '../src/widgets/layout';

const appWidgets = widgetsFromFiles([
  { id: 'notes', component: NotesWidget, meta: notesWidgetMeta },
]);

export { appWidgetLayout, appWidgets };
