/* @layer electron-main @kind constants */
const REVIEW_IDLE_MS = 30_000;
const REVIEW_START_MS = 60_000;
const REVIEW_QUIT_GRACE_MS = 5000;
const REVIEW_SPLASH_STEP = 'splash';
const SPLASH_SHOT_TIMEOUT_MS = 5000;
const FAILED_STATUS = 400;
const REPORT_JSON = 'report.json';
const REPORT_MARKDOWN = 'report.md';

export { FAILED_STATUS, REPORT_JSON, REPORT_MARKDOWN, REVIEW_IDLE_MS, REVIEW_QUIT_GRACE_MS, REVIEW_SPLASH_STEP, REVIEW_START_MS, SPLASH_SHOT_TIMEOUT_MS };
