/* @layer tooling-scripts @kind test */
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { loadPlugins } from '../src/plugins/load-plugins.mjs';
import { checkPublishStyle } from '../src/pr/style.mjs';

const made = [];

const tree = (files) => {
  const root = mkdtempSync(join(tmpdir(), 'brock-plugins-'));
  made.push(root);
  for (const [file, text] of Object.entries(files)) {
    mkdirSync(dirname(join(root, file)), { recursive: true });
    writeFileSync(join(root, file), text);
  }
  return root;
};

const plugin = (name, verb) => `export default { name: '${name}', verbs: { ${verb}: { run: () => 0 } } };\n`;

afterEach(() => {
  for (const root of made.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe('loadPlugins', () => {
  it('finds tools/brock-plugin-*/index.mjs inside any top-level dot-folder', async () => {
    const root = tree({
      'package.json': '{}',
      '.one/tools/brock-plugin-a/index.mjs': plugin('a', 'alpha'),
      '.two/tools/brock-plugin-b/index.mjs': plugin('b', 'beta'),
      '.two/tools/other/index.mjs': plugin('c', 'gamma'),
      'plain/tools/brock-plugin-d/index.mjs': plugin('d', 'delta'),
    });
    const { plugins, verbs } = await loadPlugins(root, { plugins: [] });
    expect(plugins.map((entry) => entry.name)).toEqual(['a', 'b']);
    expect(Object.keys(verbs)).toEqual(['alpha', 'beta']);
  });

  it('loads a plugin folder found in two dot-folders once', async () => {
    const root = tree({
      'package.json': '{}',
      '.one/tools/brock-plugin-a/index.mjs': plugin('a', 'alpha'),
      '.two/tools/brock-plugin-a/index.mjs': plugin('a', 'alpha'),
    });
    expect((await loadPlugins(root, { plugins: [] })).plugins).toHaveLength(1);
  });
});

describe('checkPublishStyle', () => {
  const plainWorkspace = { publish: { prStyle: 'plain' } };

  it('rejects a co-author or generated-by trailer and the robot emoji', () => {
    for (const text of ['Fix it\n\nCo-authored-by: someone <a@b.c>', 'Fix it\n\nGenerated with some tool', 'Fix it\n\n[Generated by a tool](https://example.com)', 'Fix it \u{1F916}']) {
      expect(() => checkPublishStyle(text, 'The PR body', plainWorkspace), text).toThrow(/attribution or co-author line/);
    }
  });

  it('accepts a sentence that says a file is generated by the build', () => {
    expect(() => checkPublishStyle('The manifest is generated by the build.', 'The PR body', plainWorkspace)).not.toThrow();
  });});
