name: release

on:
  push:
    branches: [main]

concurrency: release

jobs:
  release:
    uses: drizztdourden08/standards/.github/workflows/release.yml@v0
    secrets: inherit
    permissions:
      contents: write
      packages: write
      pull-requests: write
